### ISSUE TITLE
Error | SaneEconomy 0.8.0

### ISSUE THREAD

**Issue by TrademarkTM** [AppleDash/SaneEconomy#17]
Hello.
I updated my SaneEconomy to 0.8.0 today, and it causes an error. The plugins loads normally (I'm using Java 8 as well):

```
22.09 17:12:26 [Server] INFO [SaneEconomy] Enabling SaneEconomy v0.8.0
22.09 17:12:26 [Server] INFO [SaneEconomy] Initializing currency...
22.09 17:12:26 [Server] INFO [SaneEconomy] Initialized currency: dollars
22.09 17:12:26 [Server] INFO [SaneEconomy] Initializing economy storage backend...
22.09 17:12:26 [Server] INFO [SaneEconomy] Initialized flatfile backend with file /plugins/SaneEconomy/economy.db
22.09 17:12:26 [Server] INFO [SaneEconomy] Performing initial data load...
22.09 17:12:26 [Server] INFO [SaneEconomy] Data loaded!
22.09 17:12:26 [Server] INFO [SaneEconomy] Initializing commands...
22.09 17:12:26 [Server] INFO [SaneEconomy] Initialized commands.
22.09 17:12:26 [Server] INFO [SaneEconomy] Initializing listeners...
22.09 17:12:26 [Server] INFO [SaneEconomy] Initialized listeners.
22.09 17:12:26 [Server] INFO [SaneEconomy] Hooked into Vault.
```

But when I use /eco command, it causes this error (and it actually gives me the money):

```
22.09 17:13:18 [Server] ERROR null
22.09 17:13:18 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'eco' in plugin SaneEconomy v0.8.0
22.09 17:13:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
22.09 17:13:18 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
22.09 17:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
22.09 17:13:18 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot transact a zero or negative amount!
22.09 17:13:18 [Server] INFO at org.appledash.saneeconomy.economy.transaction.Transaction.<init>(Transaction.java:17) ~[?:?]
22.09 17:13:18 [Server] INFO at org.appledash.saneeconomy.command.type.EconomyAdminCommand.onCommand(EconomyAdminCommand.java:117) ~[?:?]
22.09 17:13:18 [Server] INFO at org.appledash.saneeconomy.command.SaneEconomyCommand.onCommand(SaneEconomyCommand.java:30) ~[?:?]
22.09 17:13:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
22.09 17:13:18 [Server] INFO ... 15 more
```
- Works normally
- I used the command "/eco set TrademarkTM 10000"
- I'm hooking with Vault
- No problem with other plugins

Hope you fix it soon!
Thanks!

**Comment by AppleDash** [comment]
I will look into this this evening, thanks!

**Comment by AppleDash** [comment]
Give 0.8.1 a try :)
