### ISSUE TITLE
Once again, another error

### ISSUE THREAD

**Issue by TrademarkTM** [AppleDash/SaneEconomy#18]
```
23.09 18:32:34 [Server] ERROR null
23.09 18:32:34 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'eco' in plugin SaneEconomy v0.8.1
23.09 18:32:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
23.09 18:32:34 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
23.09 18:32:34 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
23.09 18:32:34 [Server] INFO Caused by: java.lang.NullPointerException
23.09 18:32:34 [Server] INFO at org.appledash.saneeconomy.command.type.EconomyAdminCommand.onCommand(EconomyAdminCommand.java:123) ~[?:?]
23.09 18:32:34 [Server] INFO at org.appledash.saneeconomy.command.SaneEconomyCommand.onCommand(SaneEconomyCommand.java:30) ~[?:?]
23.09 18:32:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
23.09 18:32:34 [Server] INFO ... 15 more
```
- Version: 1.8.8 with ViaVersion
- NullPointerException

Hope you fix it!

**Comment by AppleDash** [comment]
Give https://github.com/AppleDash/SaneEconomy/releases/tag/0.8.2 a try :)
