### ISSUE TITLE
new players can see own bal but admin cannot see new player balance

### ISSUE THREAD

**Issue by foosratt** [AppleDash/SaneEconomy#20]
So I am updated to 0.8.2 and when a new player comes on they can now see their balance themselves but as admin I cannot see their balance until the user logs out and logs back in.  I THINK that the issue is at......

PlayerUtils.java  Line 32

if ((player != null) && !player.hasPlayedBefore()) {

I am just getting into the source now but this seems odd in that player has never played before we should still be able to get the player information from Bukkit. 

On a side note can I get some information as to how to get the git repository to create a jar file.  I have it cloned and in eclipse but when I run mvn package or any of the other goals I cannot get a jar file built.

**Comment by AppleDash** [comment]
This seems to be a common problem - I'll have to do some testing of my own. If a player has never played before, then there is no information to get from Bukkit. However, if they are online, then it should work fine.

`mvn package` is what you want - The JAR will end up in the root project folder in the `out` folder.

**Comment by foosratt** [comment]
This is what I am seeing with mvn package......

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] SaneEconomy ........................................ SUCCESS [  0.002 s]
[INFO] SaneEconomyCore .................................... FAILURE [  0.659 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.744 s
[INFO] Finished at: 2016-09-30T20:38:27-04:00
[INFO] Final Memory: 7M/17M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project SaneEconomyCore: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR]

a build with -e results.....

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] SaneEconomy ........................................ SUCCESS [  0.001 s]
[INFO] SaneEconomyCore .................................... FAILURE [  0.669 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.754 s
[INFO] Finished at: 2016-09-30T20:39:37-04:00
[INFO] Final Memory: 7M/17M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project SaneEconomyCore: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project SaneEconomyCore: Fatal error compiling
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal error compiling
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:836)
        at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:153)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.codehaus.plexus.compiler.CompilerException: invalid target release: 1.8
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:172)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:825)
        ... 23 more
Caused by: java.lang.IllegalArgumentException: invalid target release: 1.8
        at com.sun.tools.javac.main.RecognizedOptions$GrumpyHelper.error(RecognizedOptions.java:88)
        at com.sun.tools.javac.main.RecognizedOptions$10.process(RecognizedOptions.java:359)
        at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:242)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:199)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:68)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:123)
        ... 25 more
[ERROR]

**Comment by AppleDash** [comment]
Install Java 8 JDK (not JRE, and not Java 7)

**Comment by foosratt** [comment]
$ java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

So you are aware. I am a software engineer with 20 years experience :)

**Comment by AppleDash** [comment]
No matter if you have 20 minutes or 20 lifetimes of experience, we all still make mistakes.

I recommend you look into your own system's configuration and see if anything's wrong. Can you compile other Maven projects?

Here's what I get:

```
$ java -version
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

$ mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] SaneEconomy
[INFO] SaneEconomyCore
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building SaneEconomy 0.8.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building SaneEconomyCore 0.8.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ SaneEconomyCore ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ SaneEconomyCore ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 46 source files to /home/appledash/projects/SaneEconomy/SaneEconomyCore/target/classes
[INFO] /home/appledash/projects/SaneEconomy/SaneEconomyCore/src/main/java/org/appledash/saneeconomy/utils/MySQLConnection.java: Some input files use or override a deprecated API.
[INFO] /home/appledash/projects/SaneEconomy/SaneEconomyCore/src/main/java/org/appledash/saneeconomy/utils/MySQLConnection.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/appledash/projects/SaneEconomy/SaneEconomyCore/src/main/java/org/appledash/saneeconomy/economy/backend/type/EconomyStorageBackendFlatfile.java: /home/appledash/projects/SaneEconomy/SaneEconomyCore/src/main/java/org/appledash/saneeconomy/economy/backend/type/EconomyStorageBackendFlatfile.java uses unchecked or unsafe operations.
[INFO] /home/appledash/projects/SaneEconomy/SaneEconomyCore/src/main/java/org/appledash/saneeconomy/economy/backend/type/EconomyStorageBackendFlatfile.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ SaneEconomyCore ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/appledash/projects/SaneEconomy/SaneEconomyCore/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ SaneEconomyCore ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ SaneEconomyCore ---
[INFO] Surefire report directory: /home/appledash/projects/SaneEconomy/SaneEconomyCore/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.appledash.saneeconomy.test.EconomableTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.036 sec
Running org.appledash.saneeconomy.test.NumberUtilsTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec
Running org.appledash.saneeconomy.test.CurrencyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.appledash.saneeconomy.test.EconomyManagerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 sec

Results :

Tests run: 9, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ SaneEconomyCore ---
[INFO] Building jar: /home/appledash/projects/SaneEconomy/out/SaneEconomyCore-0.8.2-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] SaneEconomy ........................................ SUCCESS [  0.001 s]
[INFO] SaneEconomyCore .................................... SUCCESS [  3.077 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.148 s
[INFO] Finished at: 2016-09-30T21:05:18-04:00
[INFO] Final Memory: 18M/281M
[INFO] ------------------------------------------------------------------------
```

**Comment by foosratt** [comment]
let me try updating my java SDK.  I am at build 51 while your are at 102

**Comment by AppleDash** [comment]
BTW, I now understand where you were going with `hasPlayedBefore()`. I've pushed another fix that checks if they've played before or if they are currently online.

**Comment by foosratt** [comment]
I updated the JDK and it looks like I am seeing a problem with the one of the test possible....

[INFO] Building SaneEconomy 0.8.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building SaneEconomyCore 0.8.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ SaneEconomyCore ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ SaneEconomyCore ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ SaneEconomyCore ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\cygwin64\home\rcrerie\workspaces\SaneEconomyWS\SaneEconomy\SaneEconomyCore\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ SaneEconomyCore ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ SaneEconomyCore ---
[INFO] Surefire report directory: C:\cygwin64\home\rcrerie\workspaces\SaneEconomyWS\SaneEconomy\SaneEconomyCore\target\surefire-reports

---

##  T E S T S

org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.UnsupportedClassVersionError: org/appledash/saneeconomy/test/CurrencyTest : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
        at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:95)
        at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:194)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:92)
        ... 9 more

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] SaneEconomy ........................................ SUCCESS [  0.001 s]
[INFO] SaneEconomyCore .................................... FAILURE [  3.185 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.277 s
[INFO] Finished at: 2016-09-30T21:14:24-04:00
[INFO] Final Memory: 8M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project SaneEconomyCore: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :SaneEconomyCore

rcrerie@homeratt ~/workspaces/SaneEconomyWS/SaneEconomy
$ clear

rcrerie@homeratt ~/workspaces/SaneEconomyWS/SaneEconomy
$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

rcrerie@homeratt ~/workspaces/SaneEconomyWS/SaneEconomy
$ mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] SaneEconomy
[INFO] SaneEconomyCore
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building SaneEconomy 0.8.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building SaneEconomyCore 0.8.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ SaneEconomyCore ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ SaneEconomyCore ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ SaneEconomyCore ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\cygwin64\home\rcrerie\workspaces\SaneEconomyWS\SaneEconomy\SaneEconomyCore\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ SaneEconomyCore ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ SaneEconomyCore ---
[INFO] Surefire report directory: C:\cygwin64\home\rcrerie\workspaces\SaneEconomyWS\SaneEconomy\SaneEconomyCore\target\surefire-reports

---

##  T E S T S

org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.UnsupportedClassVersionError: org/appledash/saneeconomy/test/CurrencyTest : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
        at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:95)
        at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:194)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:92)
        ... 9 more

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] SaneEconomy ........................................ SUCCESS [  0.001 s]
[INFO] SaneEconomyCore .................................... FAILURE [  1.083 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.169 s
[INFO] Finished at: 2016-09-30T21:15:32-04:00
[INFO] Final Memory: 8M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project SaneEconomyCore: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :SaneEconomyCore

rcrerie@homeratt ~/workspaces/SaneEconomyWS/SaneEconomy
$

**Comment by AppleDash** [comment]
Oh boy, that's a fun one.

This seems to be that your Java compiler and Java runtime are now different versions. I really can't provide too much support on this as I don't know much about your system or OS, but whatever you just did to update your JDK, do it to update JRE too.

**Comment by foosratt** [comment]
OK cleaning up my environment now.  Late where I am now so I'll check back in tomorrow sometime. Thanks for working with me.  It would be great to get this working on our sever.  It is new and we are ironing out bugs now before pushing it hard live.  Thanks again.

**Comment by AppleDash** [comment]
Not a problem, let me know how you fare!

**Comment by foosratt** [comment]
OK so I am able to build the jar file now.  The balance problem is now fixed with your latest code changes.  I am still seeing a problem with not being able to rank up with GameRanks and the cost of the rank being 0.   I am going to get the GameRanks source and look into that as to why that might be happening.  Thanks for the help with building and fixing the bugs quickly.

**Comment by foosratt** [comment]
Bal command works now for the new player AND the admin now. Closing as fixed.  Let me know when you have another official build out.
