### ISSUE TITLE
Invalid Schema Error is hosing my server

### ISSUE THREAD

**Issue by Taien** [AppleDash/SaneEconomy#51]
So I just switched over to your economy plugin after having been using a default essentials setup.  I'm updating a bunch of old plugins I wrote for 1.8 and earlier, and they depend on a Vault-based economy.  For some reason, I'm getting the following error when the server starts, and because of this my plugins are not loading because Vault is not finding SaneEconomy (as it has error'ed out).

Here is the log of the error:

`[00:58:29] [Server thread/INFO]: [Vault] Enabling Vault v1.5.6-b49
[00:58:29] [Server thread/INFO]: [Vault] [Permission] PermissionsEx found: Waiting
[00:58:29] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[00:58:29] [Server thread/INFO]: [Vault] [Chat] PermissionsEx found: Waiting
[00:58:29] [Server thread/INFO]: [Vault] Enabled Version 1.5.6-b49
[00:58:29] [Server thread/INFO]: [SaneEconomy] Enabling SaneEconomy v0.12.3
[00:58:29] [Server thread/INFO]: [SaneEconomy] No translations file found at 'C:\Users\dedicated\Desktop\Bukkit Server (Premade) 1.11.2\plugins\SaneEconomy\messages.yml' (this is not an error) - using default identity I18n.
[00:58:29] [Server thread/INFO]: [SaneEconomy] Initializing currency...
[00:58:29] [Server thread/INFO]: [SaneEconomy] Initialized currency: dollars
[00:58:29] [Server thread/INFO]: [SaneEconomy] Initializing economy storage backend...
[00:58:29] [Server thread/WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[00:58:30] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[00:58:30] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[00:58:30] [Server thread/WARN]: [AutoSaveWorld] Plugin SaneEconomy attempted to establish connection socket://127.0.0.1:3306 in main server thread
[00:58:30] [Server thread/INFO]: Initialized Hikari data source.
[00:58:30] [Server thread/INFO]: [SaneEconomy] Initialized MySQL backend.
[00:58:30] [Server thread/INFO]: [SaneEconomy] Testing connection...
[00:58:30] [Server thread/INFO]: [SaneEconomy] Connection successful!
[00:58:30] [Server thread/INFO]: [SaneEconomy] Performing initial data load...
[00:58:30] [Server thread/ERROR]: Error occurred while enabling SaneEconomy v0.12.3 (Is it up to date?)
java.lang.RuntimeException: Invalid database schema!
	at org.appledash.saneeconomy.economy.backend.type.EconomyStorageBackendMySQL.createTables(EconomyStorageBackendMySQL.java:41) ~[?:?]
	at org.appledash.saneeconomy.economy.backend.type.EconomyStorageBackendMySQL.reloadDatabase(EconomyStorageBackendMySQL.java:79) ~[?:?]
	at org.appledash.saneeconomy.utils.SaneEconomyConfiguration.loadEconomyBackend(SaneEconomyConfiguration.java:51) ~[?:?]
	at org.appledash.saneeconomy.SaneEconomy.loadConfig(SaneEconomy.java:107) ~[?:?]
	at org.appledash.saneeconomy.SaneEconomy.onEnable(SaneEconomy.java:47) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`  

Here is my config file(minus the relevant database details):
`backend:
  type: mysql
  host: ****
  port: ****
  database: ****
  username: ****
  password: ****
  table_prefix: economy_
  useSsl: true
currency:
  name:
    singular: dollar
    plural: dollars
  balance-format: ${1}
  format: '0.00'
  grouping: 3
  grouping-separator: ','
chat:
  prefix: '&b[&9Economy&b]&r '
economy:
  start-balance: 100.0
  notify-start-balance: true
  server-account: $SERVER$
debug: false
`

**Comment by AppleDash** [comment]
Give this a go! https://github.com/AppleDash/SaneEconomy/releases/tag/0.12.5-PRE

**Comment by Taien** [comment]
Now I'm getting one on another line :)

`[02:12:06] [Server thread/ERROR]: Error occurred while enabling SaneEconomy v0.12.5 (Is it up to date?)
java.lang.RuntimeException: Invalid database schema!
	at org.appledash.saneeconomy.economy.backend.type.EconomyStorageBackendMySQL.createTables(EconomyStorageBackendMySQL.java:40) ~[?:?]
	at org.appledash.saneeconomy.economy.backend.type.EconomyStorageBackendMySQL.reloadDatabase(EconomyStorageBackendMySQL.java:78) ~[?:?]
	at org.appledash.saneeconomy.utils.SaneEconomyConfiguration.loadEconomyBackend(SaneEconomyConfiguration.java:51) ~[?:?]
	at org.appledash.saneeconomy.SaneEconomy.loadConfig(SaneEconomy.java:116) ~[?:?]
	at org.appledash.saneeconomy.SaneEconomy.onEnable(SaneEconomy.java:47) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

**Comment by Taien** [comment]
Oh wait, that's probably the same statement, eh

**Comment by Taien** [comment]
Check out the pics [here](http://imgur.com/a/26wCI) from HeidiSQL after the error occurs, let me know if this is how they should look

**Comment by AppleDash** [comment]
Try deleting the SaneEconomy tables and then giving it another go!

**Comment by AppleDash** [comment]
Any luck, @Taien ?

**Comment by Taien** [comment]
Sorry, I had further issues with the plugin that same night so I just
developed my own solution instead.  So I didn't get to actually test it.
Nothing personal, I just have always preferred to code my own stuff when I
can't get someone else's to work.  The other issue we were having was a
"group 5 does not exist" error when running the plugin in json mode.  But
like I said, I just developed my own Vault-hooking econ as a replacement.
The server is pretty custom anyway.  Thanks for the replies and quick fixes.

**Comment by AppleDash** [comment]
I wish you the best of luck with the many, many subtle issues and bugs you'll most likely encounter along the way - it's not as easy as it looks, as I found with this project :)
