### ISSUE TITLE
error on /baltop command

### ISSUE THREAD

**Issue by EverNife** [AppleDash/SaneEconomy#56]
I am getting this console error when trying to use ```/baltop```

```[00:10:49] [Server thread/INFO]: EverNife issued server command: /baltop
[00:10:49] [Craft Scheduler Thread - 702/WARN]: [SaneEconomy] Plugin SaneEconomy v0.12.7 generated an exception while executing task 37624
java.lang.IllegalArgumentException: PartialName cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.matchPlayer(CraftServer.java:469) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.getWorldDataByPlayerName(WorldsHolder.java:473) ~[?:?]
	at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.getWorldPermissionsByPlayerName(WorldsHolder.java:527) ~[?:?]
	at net.milkbowl.vault.permission.plugins.Permission_GroupManager.playerHas(Permission_GroupManager.java:103) ~[?:?]
	at net.milkbowl.vault.permission.Permission.has(Permission.java:61) ~[?:?]
	at net.milkbowl.vault.permission.Permission.playerHas(Permission.java:130) ~[?:?]
	at org.appledash.saneeconomy.vault.VaultHook.hasPermission(VaultHook.java:34) ~[?:?]
	at org.appledash.saneeconomy.economy.EconomyManager.lambda$getTopPlayerBalances$1(EconomyManager.java:206) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_121]
	at org.appledash.saneeconomy.economy.EconomyManager.getTopPlayerBalances(EconomyManager.java:203) ~[?:?]
	at org.appledash.saneeconomy.command.BalanceTopCommand.onCommand(BalanceTopCommand.java:58) ~[?:?]
	at org.appledash.saneeconomy.shaded.sanelib.command.SaneCommand.lambda$onCommand$0(SaneCommand.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]```

There is not output for the user, just doesnt happen anything

**Comment by EverNife** [comment]
Now that i was reading the commits i sow this one https://github.com/AppleDash/SaneEconomy/commit/1f0df591fd51e631dc7e6b3d1ae6abcfba3562e9 :/

Feel free to close if it is already solved.

**Comment by AppleDash** [comment]
This will be fixed in latest release :) - Coming tonight
