### ISSUE TITLE
Hostname in certificate didn't match: <mvn.votuvo.com> != <repo.votuvo.com>

### ISSUE THREAD

**Issue by bayuah** [AppleDash/SaneEconomy#63]
Hi, I try to build it for myself.

It seem the repo in pom.xml is inaccessible.

```
[WARNING] Could not transfer metadata org.spigotmc:spigot-api:1.12-R0.1-SNAPSHOT/maven-metadata.xml from/to votuvo (https://mvn.votuvo.com/): hostname in certificate didn't match: <mvn.votuvo.com> != <repo.votuvo.com> OR <repo.votuvo.com>
[WARNING] Could not transfer metadata org.appledash:sanelib:0.3.6-SNAPSHOT/maven-metadata.xml from/to votuvo (https://mvn.votuvo.com/): hostname in certificate didn't match: <mvn.votuvo.com> != <repo.votuvo.com> OR <repo.votuvo.com>
```
I can work around it by compiling each dependency and put it in my cache.

But, I found a difficulty for `sanelib`. I did try forking from `https://github.com/AppleDash/SaneLib`, but it still look failed, even though I did success compiling it.

This is my server log:

```
[02:58:39] [Server thread/ERROR]: Error occurred while enabling SaneEconomy v${project.version} (Is it up to date?)
java.lang.NoClassDefFoundError: org/appledash/saneeconomy/shaded/hikari/HikariConfig
	at org.appledash.saneeconomy.shaded.sanelib.database.SaneDatabase.initDataSource(SaneDatabase.java:67) ~[?:?]
	at org.appledash.saneeconomy.shaded.sanelib.database.SaneDatabase.<init>(SaneDatabase.java:28) ~[?:?]
	at org.appledash.saneeconomy.utils.database.MySQLConnection.<init>(MySQLConnection.java:23) ~[?:?]
	at org.appledash.saneeconomy.economy.backend.type.EconomyStorageBackendMySQL.<init>(EconomyStorageBackendMySQL.java:26) ~[?:?]
	at org.appledash.saneeconomy.utils.SaneEconomyConfiguration.loadBackend(SaneEconomyConfiguration.java:91) ~[?:?]
	at org.appledash.saneeconomy.utils.SaneEconomyConfiguration.loadEconomyBackend(SaneEconomyConfiguration.java:43) ~[?:?]
	at org.appledash.saneeconomy.SaneEconomy.loadConfig(SaneEconomy.java:173) ~[?:?]
	at org.appledash.saneeconomy.SaneEconomy.onEnable(SaneEconomy.java:55) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[custom18.jar:git-Spigot-93e20b3-b8f84f3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [custom18.jar:git-Spigot-93e20b3-b8f84f3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [custom18.jar:git-Spigot-93e20b3-b8f84f3]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [custom18.jar:git-Spigot-93e20b3-b8f84f3]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [custom18.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [custom18.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [custom18.jar:git-Spigot-93e20b3-b8f84f3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: org.appledash.saneeconomy.shaded.hikari.HikariConfig
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[custom18.jar:git-Spigot-93e20b3-b8f84f3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[custom18.jar:git-Spigot-93e20b3-b8f84f3]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	... 16 more
```
Thank you.

**Comment by MedicOP** [comment]
https://github.com/AppleDash/SaneEconomy/pull/50

**Comment by AppleDash** [comment]
All good now.

**Comment by bayuah** [comment]
Awesome!
