### ISSUE TITLE
mysql dont work

### ISSUE THREAD

**Issue by xMaZax** [AppleDash/SaneEconomy#69]
[14:40:02] [Server thread/INFO]: [SaneEconomy] Enabling SaneEconomy v0.13.1-SNAPSHOT
[14:40:02] [Server thread/INFO]: [SaneEconomy] Using YAML-backed I18n from /var/server/lobby/plugins/SaneEconomy/messages.yml
[14:40:02] [Server thread/INFO]: [SaneEconomy] Initializing currency...
[14:40:02] [Server thread/INFO]: [SaneEconomy] Initialized currency: dollars
[14:40:02] [Server thread/INFO]: [SaneEconomy] Initializing economy storage backend...
[14:40:02] [Server thread/WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[14:40:02] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[14:40:02] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[14:40:03] [Server thread/ERROR]: Error occurred while enabling SaneEconomy v0.13.1-SNAPSHOT (Is it up to date?)
org.appledash.saneeconomy.shaded.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.appledash.saneeconomy.shaded.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516) ~[?:?]
	at org.appledash.saneeconomy.shaded.hikari.pool.HikariPool.<init>(HikariPool.java:118) ~[?:?]
	at org.appledash.saneeconomy.shaded.hikari.HikariDataSource.<init>(HikariDataSource.java:71) ~[?:?]
	at org.appledash.saneeconomy.shaded.sanelib.database.SaneDatabase.initDataSource(SaneDatabase.java:97) ~[?:?]
	at org.appledash.saneeconomy.shaded.sanelib.database.SaneDatabase.<init>(SaneDatabase.java:28) ~[?:?]
	at org.appledash.saneeconomy.utils.database.MySQLConnection.<init>(MySQLConnection.java:23) ~[?:?]
	at org.appledash.saneeconomy.economy.backend.type.EconomyStorageBackendMySQL.<init>(EconomyStorageBackendMySQL.java:26) ~[?:?]
	at org.appledash.saneeconomy.utils.SaneEconomyConfiguration.loadBackend(SaneEconomyConfiguration.java:91) ~[?:?]
	at org.appledash.saneeconomy.utils.SaneEconomyConfiguration.loadEconomyBackend(SaneEconomyConfiguration.java:43) ~[?:?]
	at org.appledash.saneeconomy.SaneEconomy.loadConfig(SaneEconomy.java:173) ~[?:?]
	at org.appledash.saneeconomy.SaneEconomy.onEnable(SaneEconomy.java:55) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Paper-1270]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [spigot.jar:git-Paper-1270]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Paper-1270]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot.jar:git-Paper-1270]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot.jar:git-Paper-1270]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:226) [spigot.jar:git-Paper-1270]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-Paper-1270]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2222) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2017) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot.jar:git-Paper-1270]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[spigot.jar:git-Paper-1270]
	at org.appledash.saneeconomy.shaded.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
	at org.appledash.saneeconomy.shaded.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[?:?]
	at org.appledash.saneeconomy.shaded.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[?:?]
	... 18 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_151]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_151]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_151]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_151]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_151]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_151]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2222) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2017) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot.jar:git-Paper-1270]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389) ~[spigot.jar:git-Paper-1270]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[spigot.jar:git-Paper-1270]
	at org.appledash.saneeconomy.shaded.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
	at org.appledash.saneeconomy.shaded.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[?:?]
	at org.appledash.saneeconomy.shaded.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[?:?]
	... 18 more
[14:40:03] [Server thread/INFO]: [SaneEconomy] Disabling SaneEconomy v0.13.1-SNAPSHOT

**Comment by DrkMatr1984** [comment]
Bump, Just started with latest version. Works on first connection, then all other connections after server restarts fail. I think it has to do with the timeout time being extremely low, but now sure. For now, downgrading a few versions.

**Comment by AppleDash** [comment]
@DrkMatr1984 Timeout is 5 seconds, if your queries are taking more than 5 seconds... You have a bad MySQL server.

I believe this issue is a bad MySQL server.

**Comment by DrkMatr1984** [comment]
That might be, I'm connecting remotely for now over SSH tunnel to my VPS until production. You can close issue for now, and if anyone else reports we can do further testing.
