### ISSUE TITLE
I get an error everytime I use /saneeconomy /ecoadmin well anything to do with Sane

### ISSUE THREAD

**Issue by AnoKira** [AppleDash/SaneEconomy#7]
**Here is the error, could you fix it or tell me what's wrong please**
[06:07:36 INFO]: AnoKira issued server command: /saneeconomy

org.bukkit.command.CommandException: Unhandled exception executing command 'saneeconomy' in plugin SaneEconomy v0.6.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:625) ~[craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1299) [craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1159) [craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:692) [craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:647) [craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:551) [craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
        at org.appledash.saneeconomy.utils.MessageUtils.sendMessage(MessageUtils.java:20) ~[?:?]
        at org.appledash.saneeconomy.command.SaneEconomyCommand.onCommand(SaneEconomyCommand.java:26) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
        at org.appledash.saneeconomy.utils.MessageUtils.sendMessage(MessageUtils.java:20) ~[?:?]
        at org.appledash.saneeconomy.command.SaneEconomyCommand.onCommand(SaneEconomyCommand.java:26) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.10.2-R0.1-SNAPSHOT.jar:git-Bukkit-67b2424]
        ... 15 more

**Comment by AnoKira** [comment]
[config.zip](https://github.com/AppleDash/SaneEconomy/files/400803/config.zip)

PS sorry forgot to include the config file ^_^

**Comment by AppleDash** [comment]
Sorry about that! Try this: https://github.com/AppleDash/SaneEconomy/releases/tag/0.6.5

The error is my fault, and it's because I was using some code that only exists on Spigot, but you're using Bukkit.

**Comment by AnoKira** [comment]
Thank you so much ^_^ it works like a dream if I may ask is it possible to get a quick tutorial about this plugin also?

**Comment by AppleDash** [comment]
There's a Wiki on GitHub if you look around for the link - that has command info and permissions!

**Comment by AnoKira** [comment]
awsume thank you also if I set the start-balance in the config file any new player should receive it right?

**Comment by AppleDash** [comment]
Correct!

**Comment by AnoKira** [comment]
I made a new server and added only the config file of saneEco but I didn't receive my initial 100

**Comment by AppleDash** [comment]
In your config, start-balance is 0. If your actual config has changed now, try deleting the SaneEconomy folder and reconfiguring it.

**Comment by AnoKira** [comment]
cool will test that now thanks a million
